const API_BASE_URL = process.env.NEXT_PUBLIC_APIBASEURL;
const API_BASE_IMG_URL = process.env.NEXT_PUBLIC_APIBASEIMGURL;
const API_KEY = process.env.NEXT_PUBLIC_APIKEY;
const API_READ_ACCESS_TOKEN = process.env.NEXT_PUBLIC_APIREADACCESSTOKEN;

export { API_BASE_URL, API_BASE_IMG_URL, API_KEY, API_READ_ACCESS_TOKEN };
